# Generated by Django 2.2.6 on 2019-11-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Device Code')),
                ('name', models.CharField(max_length=25, verbose_name='Device Name')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=20, verbose_name='device')),
                ('value', models.FloatField(verbose_name='value')),
                ('data_id', models.PositiveIntegerField(verbose_name='Data ID')),
                ('record_time', models.DateTimeField(verbose_name='Record Time')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.IntegerField(verbose_name='Data ID')),
                ('record_time', models.DateTimeField(verbose_name='Record Time')),
                ('element', models.ManyToManyField(to='echo.Element')),
            ],
        ),
    ]
