# Generated by Django 2.2.6 on 2019-11-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='device',
            field=models.CharField(max_length=20, verbose_name='Device'),
        ),
    ]
