# Generated by Django 2.2.6 on 2019-11-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_auto_20191102_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='device',
            field=models.CharField(max_length=20, null=True, verbose_name='Device'),
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
