# Generated by Django 2.2.6 on 2019-11-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0003_auto_20191104_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=25, null=True, verbose_name='Device Name'),
        ),
    ]
